### ISSUE TITLE
We need to add validation for the parameters of the merge method

### ISSUE THREAD

**Issue by jt3k** [Mitranim/emerge#2]
example:
```js
merge(1, {2:2});
merge(null, {2:2});
merge('123', {2:2});
merge(undefined, {2:2});
// all lines returns => {2:2} , but it's good if warning or exception was displayed
```

**Comment by mitranim** [comment]
Huh interesting. It's true that the put/patch/merge functions are extremely permissive about what they accept; I don't recall ever having problems with this. There are places where strict validation would be more annoying than useful, but it's still worth considering. Would be interesting to hear more about your use case and what made this behavior surprising.

**Comment by jt3k** [comment]
I had a case when I used merge incorrectly but my application continued to work and did not report the problem, it was hard to find the source of the problem.

Maybe there's an option to report problems only if `NODE_ENV !== 'production'` ?

**Comment by mitranim** [comment]
Apologies for the delay.

Optional features that behave differently in development and production environments are just an invitation for unexpected breakage. I think we could make it strict by default. I'll experiment to see its effects on a large application. You could too: just clone Emerge, modify it locally, run the build, and use `npm link` to link that version into an application.

**Comment by mitranim** [comment]
Done! Starting in 0.4.0, all "update" functions have stricter input validation.

The following will still work:

```js
e.patch(undefined, {one: 10})
```

But the following will fail:

```js
e.patch('not dict', {one: 10})
```

Thanks for raising the issue. Let me know if you spot any problems.

**Comment by jt3k** [comment]
Excellent! Thank you! This will make it easier to find these errors
