### ISSUE TITLE
Suggestion: Only treat undefined as removal

### ISSUE THREAD

**Issue by icedtoast** [Mitranim/emerge#3]
Under Merge Semantics:
> In dicts, null and undefined properties are considered non-existent. Setting a property to null or undefined is the same as deleting it.

May I suggest this is changed to only consider `undefined` as non-existent?

I ask because I tend to have several objects that I want to merge, which contain null properties, but I also want to be able to remove properties, which is where undefined would be useful.

In other words; I have code which consumes a merged object that distinguishes between null and the absence of the property itself.

**Comment by mitranim** [comment]
Hello there! Glad to see some interest. I apologize for the wall of text below; it's an attempt to gather thoughts.

Interesting question. In the last year, I came across just _one_ case where property preservation mattered. In that particular case, both `null` and `undefined` had to be preserved.

There's value in making Emerge fully compatible with 3d party APIs, in the sense that it produces objects that can be passed to any code. After the removal of `Object.freeze`, implicit property elision is the last remaining incompatibility. While extremely convenient, it also bit me a few times. It's a candidate for removal, but it needs a good alternative.

Experience tells me that distinguishing `null` and `undefined` is a road to hell. No other language has this ridiculous distinction. I find that treating them equally is good at preventing gotchas. Emerge goes one step further in treating `nil` and a missing property as identical; this idea is borrowed from Swift, where setting a dict property to `nil` deletes it. That said, Emerge is currently _inconsistent_ in this treatment: `equalBy` and `equal` compare `{}` and `{blah: undefined}` as not equal; I haven't found a way to eliminate this distinction without a complexity penalty or performance penalty. Yet another argument against implicit property elision.

Thinking back, I don't recall _any_ of my code actually depending on property elision. It's more of a cosmetic cleanup feature.

One option I've been considering for a long time is to introduce functions `del` and `delIn`, symmetric to `put` and `putIn`, that remove a property. Funny fact: removing property elision and adding such functions would make Emerge almost a strict subset of `clojure.core`. Was Rich Hickey's design better all along? This has just one problem: currently, `patch` lets you add, replace, and remove properties simultaneously, while specialized removal functions might require an intermediary object or several.

Need to revisit my JS and see how it would be impacted and what APIs it wants.

**Comment by mitranim** [comment]
In version `0.5.0`, Emerge no longer auto-removes `null` and `undefined` properties. Removal is now explicit via `remove` and `removeIn`. Thanks for bringing the attention to this.
